name: Frontend E2E CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: walletdb
          POSTGRES_USER: walletuser
          POSTGRES_PASSWORD: walletpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install Cypress binary
        run: npx cypress install

      - name: Build frontend
        run: npm run build

      - name: Start frontend server
        run: npm run preview &
        env:
          NODE_ENV: test

      - name: Wait for frontend to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:5173
          timeout: 60

      - name: Login to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u Pagliaricci --password-stdin

      - name: Pull wallet-back image
        run: docker pull ghcr.io/aseca-recoleta-vie/wallet-back:latest-stable

      - name: Create Docker network
        run: docker network create wallet-test-net

      - name: Connect postgres service container to custom network
        run: |
          POSTGRES_CONTAINER_ID=$(docker ps -q --filter "ancestor=postgres:latest")
          docker network connect wallet-test-net $POSTGRES_CONTAINER_ID

      - name: Start wallet-back container
        run: |
          docker run -d --name wallet-back \
            --network wallet-test-net \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/walletdb \
            -e SPRING_DATASOURCE_USERNAME=walletuser \
            -e SPRING_DATASOURCE_PASSWORD=walletpassword \
            -p 8080:8080 \
            ghcr.io/aseca-recoleta-vie/wallet-back:latest-stable

      - name: Check if backend container is running
        run: docker ps -a

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to respond to login..."
          for i in {1..20}; do
            curl -X POST http://localhost:8080/auth/login \
              -H "Content-Type: application/json" \
              -d '{"email":"pablopagliaricci@gmail.com", "password":"Password1!"}' \
              --fail && break
            echo "Retrying... ($i)"
            docker logs wallet-back || true
            sleep 5
          done

      - name: Run Cypress tests
        run: npx cypress run