name: Frontend E2E CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: walletdb
          POSTGRES_USER: walletuser
          POSTGRES_PASSWORD: walletpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      wallet-back:
        image: ghcr.io/aseca-recoleta-vie/wallet-back:latest-stable
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
          SPRING_DATASOURCE_USERNAME: walletuser
          SPRING_DATASOURCE_PASSWORD: walletpassword
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/actuator/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout frontend
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Start frontend server
        run: npm run preview &
        env:
          NODE_ENV: test

      - name: Wait for frontend to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:4173
          timeout: 60

      - name: Wait for backend to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:8080/actuator/health
          timeout: 60

      - name: Run Cypress tests
        run: npx cypress run